export const ADD_CATEGORY = 'ADD_CATEGORY'

export const CHANGE_ACTIVE_CATEGORY = 'CHANGE_ACTIVE_CATEGORY'

export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const SHOW_POPUP = 'SHOW_POPUP'

export const HIDE_POPUP = 'HIDE_POPUP'
